name: "CI"
on:
  pull_request:
  push:
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compiler: ghc8107
          - compiler: ghc902
          - compiler: ghc924
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - run: nix -L build ".#checks.x86_64-linux.$GHCVER"
      env:
        GHCVER: ${{ matrix.compiler }}
